services:
  - type: web
    name: kimseyenemezlogbot
    env: node
    plan: free
    buildCommand: npm install && node deploy-commands.js
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: AUTO_JOIN_VOICE_CHANNEL
        sync: false
